id: A5AEA58B8
title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
type: translation
pechas:
- IB479BB05
- I046057B8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:11.982695
  last_modified_at: 2023-01-04 12:46:11.982725
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  IB479BB05/2620: 22E1
  I046057B8/9794: 22E1
